import FeatureSection from "@/components/feature-section";
import Footer from "@/components/footer";
import HeroSection from "@/components/hero-section";
import HowDoesItWorkSection from "@/components/how-does-it-work-section";
import Navbar from "@/components/navbar";
import TryItOutSections from "@/components/try-it-out-section";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import Image from "next/image";
const faqList = [
  {
    title: "How does XLip's AI naming suggestion feature work?",
    content:
      "XLip uses advanced algorithms to analyze the content of your links and suggests optimized names automatically, making it easier to share and remember.",
  },
  {
    title: "Can I customize the shortened links generated by XLip?",
    content:
      "Yes, XLip allows you to enter a custom name for your shortened links, or you can use our AI suggestion tool for personalized naming.",
  },
  {
    title: "What can I do with XLip's QR code generator?",
    content:
      "XLip's QR code generator creates dynamic QR codes that link directly to your shortened URLs, perfect for offline marketing and seamless digital engagement.",
  },
  {
    title: "How can XLip's analytics help me?",
    content:
      "XLip provides detailed analytics on your links, including click-through rates, geographic data of visitors, and device statistics, helping you understand and optimize your link performance.",
  },
  {
    title: " Is XLip secure to use for my links?",
    content:
      "Yes, XLip ensures the security and integrity of your links with advanced encryption and reliable infrastructure, ensuring safe sharing and tracking of your URLs.",
  },
];
export default function Home() {
  return (
    <div>
      <Navbar />
      <main>
        <span className="sr-only">Hero Section</span>
        <HeroSection />
        <span className="sr-only" id="features">
          Features Section
        </span>
        <FeatureSection />
        <span className="sr-only" id="how-does-it-work">
          How does it work? Section
        </span>
        <HowDoesItWorkSection />
        <span className="sr-only" id="try-it-out">
          Try it out Section
        </span>
        <TryItOutSections />
        <span className="sr-only" id="faq">
          FAQ Section
        </span>
        <section className="container prose relative z-20 my-16 max-w-5xl px-4 lg:prose-xl lg:prose-p:prose-base prose-h2:text-3xl prose-h3:text-2xl lg:p-0">
          <div className="flex flex-col lg:flex-row lg:justify-between">
            <div>
              <h2 className="font-bold text-white">FAQ</h2>
              <p className="font-bold text-white/50">
                Answers to some questions you might have.
              </p>
            </div>
            <Accordion type="single" collapsible className="w-full lg:max-w-xl">
              {faqList.map((list, index) => (
                <>
                  <AccordionItem key={index} value={`item-${index + 1}`}>
                    <AccordionTrigger className="active:text[#B48AD2] bg-[#180817] p-4 text-left text-lg font-semibold text-white/50 no-underline focus:text-white focus:no-underline">
                      {list.title}
                    </AccordionTrigger>
                    <AccordionContent className="p-4 text-white/95">
                      {list.content}
                    </AccordionContent>
                  </AccordionItem>
                </>
              ))}
            </Accordion>
          </div>
        </section>
        <span className="sr-only">Coming Soon Section</span>
        <section className="container prose relative my-16 mb-24 max-w-5xl space-y-16 px-4 lg:prose-xl lg:prose-p:prose-base prose-h2:text-3xl prose-h3:text-2xl lg:p-0">
          <h2 className="relative z-20 text-center font-bold text-white">
            <span className="text-[#823CB4]">Analytics</span> Coming Soon...
          </h2>
          <Image
            src="/coming-soon.png"
            alt="Coming Soon"
            width={0}
            height={0}
            unoptimized
            priority
            className="relative z-20 mx-auto h-auto w-full"
          />
          <Image
            src="/background-2.png"
            alt="background gradient"
            width={0}
            height={0}
            className="absolute bottom-0 left-1/2 top-1/2 z-10 h-auto w-full -translate-x-1/2 -translate-y-1/2 transform"
          />
        </section>
      </main>
      <Footer />
    </div>
  );
}
